spring:
  application:
    name: Customer API Provider
  jackson:
    deserialization:
      fail-on-unknown-properties: true
      fail-on-ignored-properties: true
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    #hibernate:
    #ddl-auto: validate
    show-sql: ${DB_SHOW_SQL:false}
application:
  initialization:
    enabled: ${APP_INITIALIZATION_ENABLED:false}
logging:
  level:
    org:
      springframework:
        test:
          context:
            cache: DEBUG
