application:
  cors:
    enabled: true
    allowed-origins:
      - '*.swagger.io'
      - '*.google.de'
  initialization:
    enabled: true
spring:
  datasource:
    url: jdbc:h2:./.local-db/customers
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
